/**
 * MM-Workbench - 初期プロジェクトデータ
 * 汎用的なインシデント対策・非対称情報型ミステリー構造
 */

import { MMProject } from "@/types/schema";

export const initialProject: MMProject = {
  title: "深海からの呼び声",
  subtitle: "合同海難対策本部、7日間の記録",
  concept:
    "現代日本の公的機関・海難救助対策本部を舞台に、背景にクトゥルフ神話のコズミックホラーが流れる協力型インシデント・LARP/マダミス。日常の海難事故から始まり、日常が非日常の怪異へ段階的に侵食されていくパニックサスペンス。",
  targetExperience:
    "・リモート通信で繋がる東京司令部と小笠原現地の職員たちが、お互いの非対称な情報（大局的データ vs 生々しい現場感覚）を持ち寄り緊迫した危機を乗り越える体験。\n・通常兵器（自衛隊）が通用しない絶望に対し、生物学的生態系（食物連鎖）と太古の伝承を融合させた前代未聞のオペレーションで世界を救うカタルシス。\n・世間一般には『奇妙な自然現象』として隠蔽・処理され、真実は通信回線を共にした6人だけが知る『語られざる英雄（アンサング・ヒーロー）』としての余韻。",
  plotSummary:
    "【発端】1ヶ月前、小笠原諸島で見られた流星雨。登場人物全員が現地で目撃し、各自小さな隕石の欠片を拾う。同時に邪神を崇拝するカルト団体が深海に沈んだ巨大コア隕石の回収を計画。\n\n【事件】現在、全電源喪失した遭難船から救難信号。東京司令部と現地救難隊（6名）が緊急回線を開設。船長『巨大生物を見た』vs ダイバー『魚の調査サンプルだ』と証言が食い違い、ダイバーは謎の重い大型冷凍ボックスを持ち去る。\n\n【展開】直後、海底から巨大物体が時速約6kmで北上を開始。海底火山の連動噴火を引き起こす。通常兵器による自衛隊の迎撃が試みられるが、物体はダイオウイカ数百体の超群体であり攻撃は完全無力化。\n\n【絶望の真相】物体が目指すのは駿河トラフ＝富士山直下。到達すれば連動して富士山が破局噴火を起こす（残り48時間）。ダイバーが持ち去った大型冷凍ボックスこそが富士山麓へ運ばれた超巨大隕石であり、物体はその信号を追って直進していた。しかし広大な富士山麓から箱を探し出す時間は物理的に残されていない。\n\n【解決】亡き教授のクジラ言語研究（クリック音の単語連結）と、島の古文書の祝詞（語順文法）が奇跡的に結合。海自大出力ソナー網を用い、太平洋全域のマッコウクジラへ『敵＋餌＋集まれ』の捕食要請メッセージを一斉放流。数千頭のマッコウクジラが集結し、怪異を捕食・沈静化させ日本壊滅を回避する。",
  gimmickOverview:
    "① 生態系の天敵（マッコウクジラ vs ダイオウイカ）を怪異撃退に転用する生物学的逆転の発想。\n② 動物言語学（『僕には鳥の言葉がわかる』）の単語連結モデルをマッコウクジラのコーダ（クリック音）に適用した暗号パズル。\n③ 神社の祝詞の拍子が、実は太古の祖先がクジラへ伝えた『捕食命令の文法ルール（語順）』そのものだったという歴史×科学のミステリー。\n④ 6人全員が知識（音韻波形、文法語順、古謡リズム、音速補正、軍用ソナー、隕石周波数）を持ち寄らないと絶対に完成しない完全協力型の情報トランプ構造。",
  playerCount: 6,
  durationHours: 3.5,
  hasGm: true,

  characters: [
    {
      id: "pc-1",
      name: "PC1: 危機管理官",
      profession: "海上保安庁 危機管理官（東京本庁）",
      roleType: "investigator",
      isCulpritCandidate: false,
      location: "headquarters",
      introduction:
        "あなたは東京本庁の危機管理官である。突如小笠原南方で発生した民間船の全電源喪失事故を受け、現地との合同対策本部を開設した。1ヶ月前の流星雨の夜、出張先の海岸で拾った黒い小さな隕石の欠片を、執務室の机の奥に大切にしまっている。",
      initialItems: [
        "黒い小さな隕石の欠片（1ヶ月前に拾得）",
        "公用暗号通信端末",
        "遭難船登録スペック表（40tプレジャー調査船型 / 風圧流リーウェイ率3〜4%）",
      ],
      capabilities: [
        {
          id: "cap-1-0",
          name: "船型スペック・風圧流（リーウェイ）特性の提示",
          description: "キャビンが高く風を受けやすい船型であり、風速の約3〜4%（約1.5ノット）で風下へ吹き流される計算を提示する。",
          targetPhase: 1,
        },
        {
          id: "cap-1-1",
          name: "防衛省・関係省庁への緊急要請",
          description: "上層部および防衛省へ働きかけ、護衛艦・潜水艦の派遣要請手続きを実行する。",
          targetPhase: 3,
        },
        {
          id: "cap-1-2",
          name: "情報統制・極秘公安照会",
          description: "救助されたダイバーたちの身元および国内移送先の貨物追跡を極秘裏に行う。",
          targetPhase: 4,
          unlockedEvidenceIds: ["ev-cult-cargo"],
        },
        {
          id: "cap-1-3",
          name: "最高機密ソナー網の開放決断",
          description: "上層部の隠蔽命令に抗い、全責任を負って大出力海底ソナー網の軍事機密開放を承認する。",
          targetPhase: 6,
        },
      ],
      handout: {
        publicProfile: "東京司令部の総指揮官。冷静沈着で公的機関の連携を統制する。",
        secretObjective: "国民のパニックを防ぎつつ、現場の命を最優先に事態を完全終息させる。",
        internalDrama: {
          pride: "国家と市民の安全を守る危機管理の最高責任者としての誇り",
          guilt: "政府上層部から下された『事実の完全隠蔽命令』を現場に課すことへの激しい葛藤",
          loss: "過去の災害対応で救えなかった現場職員への悔恨",
        },
        backgroundTimeline: "Day 1 遭難警報受信。現地との緊急回線を開設し、漂流位置の特定を指揮……",
        handoutBody:
          "国民をパニックに陥れるわけにはいかない。だが、現場を見捨てることも絶対にできない。あなたの手元には、遭難船の船型スペックがある。キャビンが高く風を強く受ける構造のため、風速の約3〜4%（約1.5ノット）で風下へ押し流される特性（リーウェイ）がある。現場の風と海流を合成しなければ現在地は分からない……",
      },
    },
    {
      id: "pc-2",
      name: "PC2: 情報通信・音響分析官",
      profession: "情報通信・音響分析官（防衛省リエゾン）",
      roleType: "investigator",
      isCulpritCandidate: false,
      location: "headquarters",
      introduction:
        "あなたは海保と防衛省を繋ぐリエゾンであり、衛星通信・深海ソナー解析のスペシャリストである。1ヶ月前、拾った隕石から微弱な周波数ノイズが発せられているのを密かに測定した経験がある。冒頭で衛星画像やAISが使えない現実的な理由を説明する。",
      initialItems: [
        "周波数スペクトログラム解析端末",
        "拾得した微小隕石",
        "気象衛星ひまわり海上風速データ（南西風15m/s）",
        "衛星捜索制約レポート",
      ],
      capabilities: [
        {
          id: "cap-2-0",
          name: "衛星・AIS使用不能の論理的説明と強風データの提示",
          description: "ひまわりの解像度限界、低軌道衛星の通過時間、全電源喪失によるAIS停波を説明し、南西風15m/s（約30ノット）による北東への吹き流しデータを提示する。",
          targetPhase: 1,
        },
        {
          id: "cap-2-1",
          name: "広域深海ソナー走査",
          description: "深海を時速約6kmで北上する未確認巨大物体の低周波シグネチャーを捕捉する。",
          targetPhase: 2,
          unlockedEvidenceIds: ["ev-sonar-shadow"],
        },
        {
          id: "cap-2-2",
          name: "音声パルス波形解析",
          description: "持ち込まれた深海音声からクリック音（コーダ）の周波数とミリ秒単位の間隔を抽出する。",
          targetPhase: 6,
          unlockedEvidenceIds: ["ev-coda-spectrogram"],
        },
        {
          id: "cap-2-3",
          name: "大出力海底ソナー網一斉放流",
          description: "合成されたメッセージを全太平洋海域へ向け最大出力で送信する。",
          targetPhase: 7,
        },
      ],
      handout: {
        publicProfile: "通信・音響データの分析責任者。あらゆる計器の異常を数値化する。",
        secretObjective: "深海の巨大物体の物理的実態を暴き、音響による唯一の対抗策を成功させる。",
        internalDrama: {
          pride: "音響データは嘘をつかないという技術者としての絶対的自負",
          guilt: "防衛省の最高機密ソナー網に裏口アクセスを持っていることへの罪悪感",
          loss: "かつて自らが設計した音響探知の遅れで失われた潜水艇の記憶",
        },
        backgroundTimeline: "Day 1 衛星・AISが使えない理由を説明し、衛星風速計から強風データを割り出す……",
        handoutBody:
          "「司令、気象衛星ひまわりでは解像度不足で20mの船は映りません。低軌道偵察衛星が上空を通過するのは4時間後、しかも雨雲で海面は見通せません。遭難船のAIS（位置発信機）も全電源喪失で停波中です！」あなたの衛星風速計によると、現場海域には秒速15m（約30ノット）の強い南西風が吹いており、船を北東方向へ時速約1.5ノットで吹き飛ばしている……",
      },
    },

    {
      id: "pc-3",
      name: "PC3: 救難艇船長",
      profession: "小笠原救難艇船長（民間海洋ガイド）",
      roleType: "investigator",
      isCulpritCandidate: false,
      location: "field",
      introduction:
        "あなたは小笠原の海を知り尽くしたベテラン漁師・ガイドであり、民間救難隊の現場リーダーである。1ヶ月前の流星雨の夜に浜で拾った光る石を、航海安全の御守りとして操舵室に祀っている。現地の海のクセと暗礁位置を熟知している。",
      initialItems: ["救難艇の操舵キー", "御守りの小さな隕石", "小笠原南西海域・暗礁分布海図"],
      capabilities: [
        {
          id: "cap-3-1",
          name: "荒天緊急出航・漂流地点Dへの急行接舷",
          description: "海流と風向から導き出した東北東の地点Dへ急行し、暗礁手前で遭難船に接舷して救出する。",
          targetPhase: 1,
          unlockedEvidenceIds: ["ev-diver-box-photo"],
        },
        {
          id: "cap-3-2",
          name: "島民避難・民間船動員",
          description: "海底火山の活発化に伴い、島民避難船の確保と海域警備を主導する。",
          targetPhase: 3,
        },
        {
          id: "cap-3-3",
          name: "小笠原古謡（捕鯨唄）の想起",
          description: "祖父から教わった古い唄のリズムから、獲物を示す拍子を思い出す。",
          targetPhase: 6,
          unlockedEvidenceIds: ["ev-folk-song-rhythm"],
        },
      ],
      handout: {
        publicProfile: "現地の海を誰よりも熟知する海の男。現場の救助活動を一手に担う。",
        secretObjective: "島民と海に出た仲間を誰一人死なせず、全員を生きて本土へ帰す。",
        internalDrama: {
          pride: "どんな荒波からも人命を救い出してきた現場の海の男としての誇り",
          guilt: "Day 1で救助時、怪しいダイバーたちと大型冷凍ボックスの島外離脱を止められなかった悔恨",
          loss: "かつての海難事故で海に沈んだ幼馴染への弔い",
        },
        backgroundTimeline: "Day 1 メーデーを受信し救難艇を出航。海流と風の計算から地点Dへ急行し救助成功……",
        handoutBody:
          "「風だけ見て北東（地点A）に行くと見失うぞ！水面下の潮に引っ張られてるはずだ。東側には危険な暗礁群（地点C）があり、風浪の三角波でそこへ突っ込んだら船は座礁沈没する。風と海流が合わさる東北東の海域（地点D）で、暗礁の手前に回り込んで抑えなきゃならねぇ！」",
      },
    },
    {
      id: "pc-4",
      name: "PC4: 海洋・気象観測員",
      profession: "気象庁 小笠原観測所 職員",
      roleType: "investigator",
      isCulpritCandidate: false,
      location: "field",
      introduction:
        "あなたは気象・海洋・火山観測の専門員である。1ヶ月前、観測所の敷地内に落下した隕石片を未知の鉱物標本として机に保管している。海洋ブイからリアルタイムの表層海流データを取得・分析する。",
      initialItems: [
        "地質・気象観測コンソール端末",
        "鉱物標本の隕石片",
        "海洋ブイ表層流速データ（黒潮支流：真東へ2.0ノット）",
      ],
      capabilities: [
        {
          id: "cap-4-0",
          name: "海洋ブイ表層海流（真東2.0ノット）の提示",
          description: "現場海域の黒潮支流が真東へ2.0ノットで流れている実測値を全員に共有する。",
          targetPhase: 1,
        },
        {
          id: "cap-4-1",
          name: "海底火山連動シミュレーション",
          description: "海底火山の噴火データから、物体の時速約6kmでの北上ペースを割り出す。",
          targetPhase: 2,
          unlockedEvidenceIds: ["ev-volcano-chain-log"],
        },
        {
          id: "cap-4-2",
          name: "破局噴火タイムリミット算出",
          description: "本土直下のマグマ溜まりへの到達時間（残り48時間）を確定させる。",
          targetPhase: 5,
          unlockedEvidenceIds: ["ev-eruption-countdown"],
        },
        {
          id: "cap-4-3",
          name: "深海水温・音速伝播補正",
          description: "水温・塩分データからソナー音速を補正し、触手群体のノイズ周波数を同定する。",
          targetPhase: 6,
        },
      ],
      handout: {
        publicProfile: "科学的データと数値を冷静に分析する観測員。感情に流されない判断を下す。",
        secretObjective: "正確なデータを提示し続け、破局噴火の発生時刻までに回避策を実行させる。",
        internalDrama: {
          pride: "正確な気象・地質予報で人命を守る科学者としての矜持",
          guilt: "最悪のカウントダウンを告げることで仲間を絶望に突き落とす苦悩",
          loss: "過去の火山噴火予報の遅れで故郷を失った記憶",
        },
        backgroundTimeline: "Day 1 局地的な表層海流データを分析。遭難船の漂流先特定に貢献……",
        handoutBody:
          "「小笠原観測所のリアルタイム海洋ブイデータです。現場海域の黒潮支流は、風とは異なり【真東へ流速2.0ノット】で流れています！つまり、海流の力だけで1時間に真東へ2.0海里押し流されている計算になります！」",
      },
    },
    {
      id: "pc-5",
      name: "PC5: 海洋生物学者",
      profession: "海洋生物研究所 准教授",
      roleType: "investigator",
      isCulpritCandidate: false,
      location: "field",
      introduction:
        "あなたは現地研究所の准教授であり、かつて『クジラ言語』を提唱して学会を追われた故・朝倉名誉教授の唯一の直弟子である。恩師の遺品である解析ノートと未発表録音テープを保管している。水温データから潮目の位置を正確に把握する。",
      initialItems: [
        "故・朝倉教授の研究ノート",
        "未発表海中録音テープ",
        "小さな隕石",
        "潮目（冷水塊境界）水温解析図",
      ],
      capabilities: [
        {
          id: "cap-5-0",
          name: "潮目境界の同定と海流減衰なしの証明",
          description: "現場海域に走る潮目により、船が本流に乗って東向きの海流2.0ノットを減衰なく受け続けていることを証明する。",
          targetPhase: 1,
        },
        {
          id: "cap-5-1",
          name: "ダイオウイカ異常生態鑑定",
          description: "船長の目撃した触手の特徴から、通常種を超える異常成長の可能性を考察する。",
          targetPhase: 1,
          unlockedEvidenceIds: ["ev-captain-testimony"],
        },
        {
          id: "cap-5-2",
          name: "超群体（コロニー）構造の看破",
          description: "通常兵器が効かない理由が『無数の個体が結合した群体』であることを看破する。",
          targetPhase: 5,
        },
        {
          id: "cap-5-3",
          name: "クジラ言語・単語波形の提供",
          description: "恩師のノートから『自分』『集まれ』のクリック音パターンを提示する。",
          targetPhase: 6,
          unlockedEvidenceIds: ["ev-asakura-notes"],
        },
      ],
      handout: {
        publicProfile: "深海生物のスペシャリスト。学会の異端児とされた恩師の研究を継ぐ。",
        secretObjective: "恩師のクジラ言語仮説の正しさを証明し、怪異を生物学的捕食で鎮める。",
        internalDrama: {
          pride: "真の海洋生態系を理解しているという研究者としてのプライド",
          guilt: "生前の恩師を世間の冷笑から庇い切れなかった後悔",
          loss: "孤独のうちに客死した恩師の存在そのもの",
        },
        backgroundTimeline: "Day 1 潮目の水温解析を行い、遭難船にかかる海流の減衰がないことを証明……",
        handoutBody:
          "「水温データから潮目の位置を割り出しました。現場海域には冷水塊との明瞭な潮目が通っており、船はその本流に乗っています。真東への海流の力（2.0ノット）は途切れることなくそのまま働いています！」",
      },
    },
    {
      id: "pc-6",
      name: "PC6: 救護班チーフ",
      profession: "現地救護ボランティア（島の旧家・神職）",
      roleType: "investigator",
      isCulpritCandidate: false,
      location: "field",
      introduction:
        "あなたは島の神社の家系であり、海難救助隊の救護チーフである。1ヶ月前、神社の境内に落下した隕石片を星の神の依代として神棚に祀っている。救難信号途絶直前の最後の微弱な無線ログを管理している。",
      initialItems: [
        "神社の古い木札",
        "救護医療キット",
        "星の依代（隕石片）",
        "途絶直前のアナログ無線音声ログ",
      ],
      capabilities: [
        {
          id: "cap-6-0",
          name: "救難無線断片ログの共有",
          description: "途絶直前の船長の声『風で舵が効かない！真横から波を受けている！』を共有し、風と海流の双方を受けている事実を提示する。",
          targetPhase: 1,
          unlockedEvidenceIds: ["ev-radio-fragment"],
        },
        {
          id: "cap-6-1",
          name: "救護聴取・精神ケア",
          description: "錯乱した船長から『海中の無数の目と触手』の証言を引き出す。",
          targetPhase: 1,
        },
        {
          id: "cap-6-2",
          name: "土蔵の古文書捜索",
          description: "先祖が遺した太古の魔物退治の古文書（祝詞）を発見する。",
          targetPhase: 6,
          unlockedEvidenceIds: ["ev-ancient-shrine-scroll"],
        },
        {
          id: "cap-6-3",
          name: "祝詞の拍子（文法ルール）詠唱",
          description: "古文書に記された点刻記号が『単語を並べる語順』であることを解き明かす。",
          targetPhase: 6,
        },
      ],
      handout: {
        publicProfile: "温和で献身的な救護担当。島の伝統や神事にも詳しい。",
        secretObjective: "島の信仰と祖先の知恵を信じ、現代科学と手を取り合って災厄を鎮める。",
        internalDrama: {
          pride: "何百年も島を守り祈り続けてきた社家としての責任感",
          guilt: "怪異の出現を単なる自然現象や錯覚として見過ごしかけた自責",
          loss: "近代化の中で失われていった島の神話や古い記憶",
        },
        backgroundTimeline: "Day 1 途絶直前の無線音声を解析し、救助後は船長の応急処置を担当……",
        handoutBody:
          "「救護本部で受信した、途絶直前の最後の微弱な無線記録です！『風で舵が効かない！真横から波（海流）を受けている！』という船長の悲鳴が残っています。船は風に煽られながら、真横から海流をまともに受けて漂流を始めた証拠です！」",
      },
    },

  ],

  evidences: [
    {
      id: "ev-drift-map",
      title: "小笠原南西海域 海図（漂流予測マップ）",
      description: "救難信号発信地点、周辺の暗礁群（東側・地点C）、および漂流予想候補（地点A:北東、地点B:東、地点C:東暗礁、地点D:東北東）が記載された海図。発信から20分経過、救助艇到着まで残り40分（計1時間の漂流）。",
      ownerId: "all",
      foundPhase: 1,
      visibility: "public",
      category: "document",
      acquisitionCondition: "Day 1: 合同救難ミーティング開始時に全体提示",
    },
    {
      id: "ev-satellite-blindspot",
      title: "気象・軌道衛星 状況報告書",
      description: "静止気象衛星『ひまわり』は広域用のため解像度不足で小型船（40t）は視認不可。低軌道偵察衛星は軌道通過まで4時間＋濃密な雨雲で光学視界ゼロ。全電源喪失でAISも停波しており、衛星頼みの捜索は不可能と断定。",
      ownerId: "pc-2",
      foundPhase: 1,
      visibility: "shareable",
      category: "document",
      acquisitionCondition: "Day 1: PC2による衛星・探査システム照会時",
    },
    {
      id: "ev-radio-fragment",
      title: "途絶直前のアナログ無線音声ログ",
      description: "救難信号途絶直前に救護班が受信したノイズ混じりの微弱音声。『メーデー！メーデー！風で舵が効かない！真横から波（海流）を受けている！計器が全部――（激しいノイズで途絶）』。風と海流の双方を強く受けている事実を示す。",
      ownerId: "pc-6",
      foundPhase: 1,
      visibility: "shareable",
      category: "audio",
      acquisitionCondition: "Day 1: PC6による救難無線ログ共有時",
    },
    {
      id: "ev-diver-box-photo",
      title: "ダイバーたちが抱えていた大型冷凍ボックス",
      description: "救助されたダイバーたちが船から持ち出した、魚釣り用の少し大型のプラスチック製冷凍ボックス（クーラーボックス）。『近辺での魚の生態調査で採集した魚が入っている。大変だったがこれで目的のものが収集できたので、これ以上は迷惑をかけない』と言い残し、直後に定期便で島外へ搬出された。魚用にしては底知れぬ異常な重量感があった。",
      ownerId: "pc-3",
      foundPhase: 1,
      visibility: "shareable",
      category: "sample",
      acquisitionCondition: "Day 1: 遭難船救助オペレーション成功時",
    },
    {
      id: "ev-captain-testimony",
      title: "遭難船船長の錯乱証言記録",
      description: "『あれはクジラなんかじゃない！海一面に巨大な目が無数に光り、無数の触手が船の計器を全部焼き切り、スクリューも完全に動かなくなった！』という録音証言。さらに『あの客たちは潜水に手慣れていたが案内したのは今回が初めてで、1ヶ月ほど前からこの海域で継続的にダイブしていた』と証言している。",
      ownerId: "pc-6",
      foundPhase: 1,
      visibility: "shareable",
      category: "testimony",
      acquisitionCondition: "Day 1: 救護所での精神ケア聴取時",
    },
    {
      id: "ev-sonar-shadow",
      title: "低周波ソナー探知記録（巨大影）",
      description: "水深800m以深を、時速約6km（約3.3ノット）の一定ペースで北上する全長数百メートルの巨大な音響シグネチャー。通常潜水艦の数倍の規模。",
      ownerId: "pc-2",
      foundPhase: 2,
      visibility: "shareable",
      category: "data",
      acquisitionCondition: "Day 2: 広域深海ソナー走査実行時",
    },
    {
      id: "ev-volcano-chain-log",
      title: "海底火山連動噴火データシート",
      description: "物体の北上ルートに沿って、西之島〜鳥島周辺の海底火山の地殻活動が連動して急激に活性化している記録。",
      ownerId: "pc-4",
      foundPhase: 2,
      visibility: "public",
      category: "data",
    },
    {
      id: "ev-cult-cargo",
      title: "国内極秘貨物追跡レポート（邪神崇拝団体）",
      description: "Day 1の大型冷凍ボックスは、特異なカルト団体によって富士山麓の山林へ極秘輸送されていた。中身は魚ではなく深海からサルベージされた超巨大コア隕石。広大すぎて捜索は時間切れ。",
      ownerId: "pc-1",
      foundPhase: 5,
      visibility: "shareable",
      category: "document",
      acquisitionCondition: "Day 5: 公安ルート極秘調査完了時",
    },
    {
      id: "ev-eruption-countdown",
      title: "破局噴火タイムリミット算出グラフ",
      description: "物体が駿河トラフ直下のマグマ溜まりに到達するまでの猶予時間はあと48時間。到達すれば連動して富士山が破局噴火を起こす。",
      ownerId: "pc-4",
      foundPhase: 5,
      visibility: "public",
      category: "data",
    },
    {
      id: "ev-asakura-notes",
      title: "故・朝倉教授のクジラ言語解析ノート",
      description: "マッコウクジラのクリック音（コーダ）は単語の連結（文法）であるという論文ドラフト。『自分（均等3連打）』『集まれ（加速4連打）』の周波数データ。",
      ownerId: "pc-5",
      foundPhase: 6,
      visibility: "shareable",
      category: "document",
    },
    {
      id: "ev-ancient-shrine-scroll",
      title: "神社の古文書（太古の盟約祝詞）",
      description: "『太古、海より触手の魔物現れしとき、島人は鯨の歌を模して海に響かせ、鯨の群れに魔物を喰らわせた』。単語の語順＝文法規則を示す点刻記号（●―●●）。",
      ownerId: "pc-6",
      foundPhase: 6,
      visibility: "shareable",
      category: "document",
    },
    {
      id: "ev-folk-song-rhythm",
      title: "小笠原古謡（捕鯨唄）の口伝メモ",
      description: "島の古い漁師唄の拍子の中に、高音で急速に連打される『餌（獲物・ご馳走）』のリズムがそのまま残されていた。",
      ownerId: "pc-3",
      foundPhase: 6,
      visibility: "shareable",
      category: "audio",
    },
    {
      id: "ev-coda-spectrogram",
      title: "実音響スペクトログラム波形シート",
      description: "恩師のテープから抽出されたクリック音の周波数と拍子。古文書の祝詞記号と重ね合わせると完全に一致する。",
      ownerId: "pc-2",
      foundPhase: 6,
      visibility: "public",
      category: "data",
    },
  ],

  timeline: [
    {
      dayNumber: 1,
      locationName: "父島南西沖 (0 km)",
      distanceKm: 0,
      situationTitle: "荒海からのメーデー・漂流予測と遭難船救助",
      incidentOverview: "民間チャーター船（40t）が突如全電源喪失。AIS停波、衛星観測不能の中、発信から1時間後の漂流地点を海流と強風のベクトル合成から特定し、暗礁手前で救助する。",
      hqResponse: "衛星死角の報告と航法計算支援。南西強風（15m/s）による風圧流（北東へ約1.5kt）と黒潮支流（真東へ2.0kt）の合成計算を実施。",
      fieldResponse: "PC3の救難艇が暗礁群（地点C）の手前、東北東の【地点D】へ急行。荒波の中で接舷し、船長とダイバーを救出成功。ダイバーは魚の調査サンプルと称して大型プラスチック冷凍ボックスを持ち去る。",
      revealedEvidenceIds: [
        "ev-drift-map",
        "ev-satellite-blindspot",
        "ev-radio-fragment",
        "ev-diver-box-photo",
        "ev-captain-testimony",
      ],
    },
    {
      dayNumber: 2,
      locationName: "西之島沖 (約180 km)",
      distanceKm: 180,
      situationTitle: "異変の顕在化・深海シグネチャー捕捉",
      incidentOverview: "西之島周辺の海底火山が異常活性化。深海ソナーに時速6kmで北上する全長数百メートルの巨大な影が捕捉される。",
      hqResponse: "低周波ソナーデータを解析。自然現象ではない未確認移動物体と暫定断定。",
      fieldResponse: "海底噴火による海水温異常を観測。移動ペースが日速約150kmと判明。",
      revealedEvidenceIds: ["ev-sonar-shadow", "ev-volcano-chain-log"],
    },
    {
      dayNumber: 3,
      locationName: "孀婦岩〜鳥島沖 (約400 km)",
      distanceKm: 400,
      situationTitle: "防衛出動の決定と隠蔽圧力",
      incidentOverview: "鳥島海底火山の噴火。物体は火山フロントを正確に北上。会議の末、海上自衛隊の武力迎撃出動を決定。",
      hqResponse: "官邸・上層部より『社会パニック防止のための完全隠蔽命令』がPC1に下る。",
      fieldResponse: "島民の避難準備を急ぐ一方、東京の隠蔽姿勢に激しい反発が起きる。",
      revealedEvidenceIds: [],
    },
    {
      dayNumber: 4,
      locationName: "須美寿島〜青ヶ島沖 (約550 km)",
      distanceKm: 550,
      situationTitle: "迎撃陣形の展開と極秘調査",
      incidentOverview: "海上自衛隊潜水艦隊が八丈島南方に展開完了。東京側はDay 1のダイバーたちの追跡調査を開始。",
      hqResponse: "公安ルートでダイバーが邪神崇拝カルトであることを掴む。",
      fieldResponse: "物体がなぜ火山の熱源・電磁波に向かって進むのか生態学的な疑問を深める。",
      revealedEvidenceIds: [],
    },
    {
      dayNumber: 5,
      locationName: "八丈島〜御蔵島沖 (約700 km)",
      distanceKm: 700,
      situationTitle: "通常兵器の敗北と絶望の真相",
      incidentOverview: "自衛隊の魚雷一斉射撃。命中するも物体はダイオウイカ数百体の超群体であり即座に再結合。通常兵器が完全無力化。",
      hqResponse: "大型冷凍ボックスの中身が『超巨大コア隕石』であり富士山麓へ運ばれたと発覚。しかし捜索は時間切れ。",
      fieldResponse: "駿河トラフ到達まで残り48時間。破局噴火までのカウントダウンを宣告。",
      revealedEvidenceIds: ["ev-cult-cargo", "ev-eruption-countdown"],
    },
    {
      dayNumber: 6,
      locationName: "三宅島〜伊豆大島沖 (約830 km)",
      distanceKm: 830,
      situationTitle: "太古の祝詞 × 恩師の音響研究の融合",
      incidentOverview: "武力敗北後、古文書の祝詞と恩師のノートが結合。クジラ言語による捕食要請メッセージと大出力ソナー作戦が立案される。",
      hqResponse: "PC1が責任を負い海自ソナー網を開放。PC2が音響コンソールを操作。",
      fieldResponse: "各自の知識（ノート、古文書、古謡、観測、隕石）を持ち寄りメッセージ文を完成。",
      revealedEvidenceIds: ["ev-asakura-notes", "ev-ancient-shrine-scroll", "ev-folk-song-rhythm", "ev-coda-spectrogram"],
    },
    {
      dayNumber: 7,
      locationName: "駿河湾口〜湾奥 (約950 km)",
      distanceKm: 950,
      situationTitle: "鯨波オペレーション決行・大捕食",
      incidentOverview: "富士山直下突入寸前、クジラ言語の捕食要請メッセージを太平洋全域へ放流。数千頭のマッコウクジラが集結し怪異を喰らい尽くす。",
      hqResponse: "全回線を同期し最大出力でソナー放流。マッコウクジラ大群の集結を確認。",
      fieldResponse: "海中の大捕食劇。怪異沈静化、海底火山の微動が停止し日本壊滅が回避される。",
      revealedEvidenceIds: [],
    },
  ],

  crypticWords: [
    {
      id: "word-self",
      symbol: "●●●",
      meaning: "自分（我ら・同族）",
      soundPattern: "均等な3連打（カッ・カッ・カッ）",
      assignedCharId: "pc-5",
      clueSource: "朝倉教授の解析ノート（基本音韻）",
    },
    {
      id: "word-gather",
      symbol: "●●●●↑",
      meaning: "集まれ（合流・急行）",
      soundPattern: "加速する4連打（カ・カ・カカッ！）",
      assignedCharId: "pc-5",
      clueSource: "朝倉教授の解析ノート（行動コーダ）",
    },
    {
      id: "word-alert",
      symbol: "━ ━",
      meaning: "警戒（危険・注意）",
      soundPattern: "低音の単発長間隔（コーン……コーン……）",
      assignedCharId: "pc-4",
      clueSource: "深海ソナー音速減衰データ",
    },
    {
      id: "word-enemy",
      symbol: "●━●●━",
      meaning: "敵（深海の触手・異形）",
      soundPattern: "不規則な乱れ打ち（カチカチッ・カカッ）",
      assignedCharId: "pc-2",
      clueSource: "群体が発する電磁ノイズシグネチャー",
    },
    {
      id: "word-prey",
      symbol: "●●●●●●",
      meaning: "餌（極上の獲物・捕食せよ）",
      soundPattern: "高音の超高速バースト（チチチチチッ）",
      assignedCharId: "pc-3",
      clueSource: "小笠原古謡（捕鯨唄の節回し）",
    },
  ],

  crypticGrammar: {
    ruleDescription: "古文書に伝わる太古の語順：『敵』＋『餌』＋『集まれ』の順序で結合することで、クジラたちへ捕食命令として伝わる。",
    correctSequence: ["word-enemy", "word-prey", "word-gather"],
    combinedMessage: "あの異形の怪異（敵）は極上のご馳走（餌）だ。集まって喰らい尽くせ！",
    holderCharId: "pc-6",
  },

  matrixLinks: [],
  lockCriteria: [
    { id: "lock-1", name: "通常兵器無効化の解明", description: "ダイオウイカ数百体の超群体であることの看破" },
    { id: "lock-2", name: "北上の真の理由特定", description: "カルトによる巨大コア隕石の富士山搬入の特定" },
    { id: "lock-3", name: "生物学的捕食手段の特定", description: "マッコウクジラ言語による捕食要請の立案" },
    { id: "lock-4", name: "言語文法の解読", description: "古文書の祝詞と音響データの結合によるメッセージ完成" },
  ],
  candidateStatuses: [],
};
